server:
  servlet:
    context-path: /blog
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: '1.0'

delete:
  secret: ${DELETE_SECRET}

logs:
  path: ${LOG_PATH:logs/}

springdoc:
  api-docs:
    enabled: true
    path: /api/swagger
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /ui/swagger
    operations-sorter: alpha
  packages-to-scan: com.codenjoy.blog.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info

git:
  directory: ${GIT_DIRECTORY}